apiVersion: v1
kind: Namespace
metadata:
  name: kdl-lab07
  labels:
    app.kubernetes.io/name: kdl-lab07
    app.kubernetes.io/part-of: kubernetes-deep-lab
    kdl/lab: "07"
    kdl/phase: api-basics
  annotations:
    kdl/description: "Kubernetes Deep Lab 07 namespace"